const params = new URLSearchParams(window.location.search);
const summaryId = params.get("summary_id");
const nodes = Object.fromEntries(["backSummary","videoTitle","videoSubline","videoStatus","videoContent","segments","videoDisclaimer","scriptMeta","regenerateButton"].map((id) => [id, document.querySelector(`#${id}`)]));
let script;
async function api(path, options={}) { const response=await fetch(path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options}); if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.detail||`请求失败：${response.status}`)} return response.json() }
async function createScript(){if(!summaryId)throw new Error("缺少总结标识，无法生成脚本。");const task=await api(`/api/three-minute-summaries/${encodeURIComponent(summaryId)}/video-scripts`,{method:"POST"});while(true){const item=await api(`/api/three-minute-summaries/video-tasks/${encodeURIComponent(task.task_id)}`);nodes.videoStatus.textContent=item.current_step||"正在生成";if(item.status==="COMPLETED")return api(`/api/three-minute-summaries/video-scripts/${encodeURIComponent(item.script_id)}`);if(item.status==="FAILED")throw new Error(item.error?.message||"脚本生成失败");await new Promise((resolve)=>setTimeout(resolve,1200))}}
function esc(value){const el=document.createElement("div");el.textContent=value||"";return el.innerHTML}
function render(){nodes.videoTitle.textContent=`${script.company.name} · ${script.period} 口播与分镜`;nodes.videoSubline.textContent=script.status==="completed"?"每一段都需要回到已确认的披露依据。":script.reason||"当前无法生成脚本。";const seconds=(script.segments||[]).reduce((total,item)=>total+item.duration_seconds,0);nodes.scriptMeta.textContent=`${script.segments?.length||0} 段 · ${seconds} 秒`;nodes.segments.innerHTML=(script.segments||[]).map((item)=>`<article class="segment"><div class="segment-no"><span>${item.segment_no}</span><small>${item.duration_seconds}秒</small></div><div><p class="panel-label">${esc(item.title)}</p><h2>${esc(item.narration)}</h2><div class="visual"><strong>画面</strong><p>${esc(item.visual_direction)}</p></div><div class="metrics">${(item.on_screen_metrics||[]).map((metric)=>`<span>${esc(metric)}</span>`).join("")}</div><small>披露依据 ${item.evidence_refs.length} 条</small></div></article>`).join("")||"<p class='empty'>暂未形成可引用的分镜。</p>";nodes.videoDisclaimer.textContent=script.disclaimer||"";nodes.videoContent.classList.remove("hidden");nodes.regenerateButton.classList.remove("hidden")}
async function boot(){nodes.backSummary.href=`./summary.html?summary_id=${encodeURIComponent(summaryId||"")}`;try{script=await createScript();render()}catch(error){nodes.videoStatus.textContent=error.message;nodes.videoStatus.className="status error"}}
nodes.regenerateButton.addEventListener("click",boot);boot();
